# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170930_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=128),
        ),
    ]
