# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated',
        ),
    ]
