# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_productinorder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
