# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinorder_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='sub_total',
        ),
    ]
