# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170926_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
    ]
