# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_images/'),
        ),
    ]
